# A
<html>
 <body>
  <p>
   Сложить два числа.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   В строке последовательно вводятся два числа, которые нужно сложить.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Одно число — результат.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1 2</pre>
     </td>
     <td>
      <pre>3</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1 -1</pre>
     </td>
     <td>
      <pre>0</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
x, y = input().split()
x = int(x)
y = int(y)
print(x + y)

# B
<html>
 <body>
  <h1>
   Больше-меньше
  </h1>
  <p>
   Вам дано выражение вида "a x b", где a и b - натуральные числа, а x - знак сравнения, '&lt;' или '&gt;'. Истинно ли данное выражение?
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   В первой строке число a, во второй знак сравнения, в третьей - число b. Оба числа - натуральные.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Если выражение истинно, выведите YES, иначе NO
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1
&lt;
2</pre>
     </td>
     <td>
      <pre>YES</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>10
&gt;
100</pre>
     </td>
     <td>
      <pre>NO</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
a = input()
x = input()
b = input()
a = int(a)
x = ord(str(x))
b = int(b)
if x==60:
	if a<b:
		print('YES')
	else:
		print('NO')
else:
	if a>b:
		print('YES')
	else:
		print('NO')

# C
<html>
 <body>
  <p>
   Определите тип треугольника (остроугольный, тупоугольный, прямоугольный) с данными сторонами.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   Даны три натуральных числа – стороны треугольника. Каждое число вводится с новой строки.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Необходимо вывести одно из слов:
  </p>
  <ul>
   <li>
    right для прямоугольного треугольника,
   </li>
   <li>
    acute для остроугольного треугольника,
   </li>
   <li>
    obtuse для тупоугольного треугольника,
   </li>
   <li>
    impossible, если треугольника с такими сторонами не существует.
   </li>
  </ul>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>3
4
5</pre>
     </td>
     <td>
      <pre>right</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
a = int(input())
b = int(input())
c = int(input())
if a+b>c and a+c>b and b+c>a:
	m = max(a, b, c)
	if m == a:
		c1, b1, a1 = a, b, c
	elif m == b:
		c1, b1, a1 = b, a, c
	elif m == c:
		c1, b1, a1 = c, a, b
	if c1**2 == a1**2 + b1**2:
		print('right')
	elif c1**2 > a1**2 + b1**2:
		print('obtuse')
	else:
		print('acute')
else:
	print('impossible')

# D
<html>
 <body>
  <p>
   Сложить все числа из потока ввода. Числа дробные, с плавающей точкой, двойной точности.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   В первой строке - целое число N &gt; 0, не превышающее 1000. Далее следует N дробных чисел, каждое в отдельной строке.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Одно число — результат суммирования.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>2
1
2</pre>
     </td>
     <td>
      <pre>3</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>3
10.99
0
-1.01</pre>
     </td>
     <td>
      <pre>9.98</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

# E
<html>
 <body>
  <h1>
   Длина удава
  </h1>
  <p>
   Требуется найти длину удава, выраженную в мартышках, попугаях или слоненках, по выбору пользователя. "Эффективная длина" попугая - 10см, мартышки - 90см, слоненка - 3м. Результат округляйте вниз, однако, если при этом получается ноль, выведите 1, чтобы не обижать удава.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   В первой строке натуральное число - длина удава в сантиметрах. Во втрой строке - "в ком измерять", "monkey", "parrot" или "elephant".
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Одно число — результат.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>200
monkey</pre>
     </td>
     <td>
      <pre>2</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>200
elephant</pre>
     </td>
     <td>
      <pre>1</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
a = int(input())
define = str(input())
parrot = 10
monkey = 90
elephant = 300
if define == 'parrot':
	si = parrot
elif define == 'monkey':
	si = monkey
elif define == 'elephant':
	si = elephant
out = int(a/si)
if out == 0:
	out = 1
print(out)