# Обработка последовательностей чисел

# A
<html>
 <body>
  <p>
   Требуется определить, является ли данный год високосным. (Год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400).
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   На вход подается натуральное число N - номер года (0 &lt; N &lt; 100000).
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Вывести YES если год високосный и NO в противном случае.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1</pre>
     </td>
     <td>
      <pre>NO</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>2000</pre>
     </td>
     <td>
      <pre>YES</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
N = int(input())

if ((N % 4 == 0) and (N % 100 != 0)) or (N % 400 == 0):
    print('YES')
else:
    print('NO')

# B
<html>
 <body>
  <p>
   Дано трехзначное число. Найдите сумму его цифр.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   Вводится трехзначное число: не меньшее 100 и не больше 999.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Одно число — сумма цифр.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>179</pre>
     </td>
     <td>
      <pre>17</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
a = int(input())
a100 = int(a/100)
a10 = int((a % (a100*100))/10)
a1 = int(a % (a100*100 + a10*10))

S = a100 + a10 + a1
print(S)

# C
<html>
 <body>
  <p>
   Определите сумму всех элементов последовательности, завершающейся числом 0.
  </p>
  <p>
   Числа, следующие за нулем, считывать не нужно.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   Вводятся элементы последовательности по одному целому числу на строку. Числа вводятся, пока не будет введен 0.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Вывести одно целое число - сумму последовательности.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>5
3
10
0</pre>
     </td>
     <td>
      <pre>18</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>17
-4
0</pre>
     </td>
     <td>
      <pre>13</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
S = 0
a = 1
while (a != 0):
	a = int(input())
	S = S + a
print(S)

# D
<html>
 <body>
  <p>
   Программа получает на вход последовательность целых неотрицательных чисел, каждое число записано в отдельной строке. 
Последовательность завершается числом 0, при считывании которого программа должна закончить свою работу и вывести 
количество членов последовательности (не считая завершающего числа 0).
Числа, следующие за числом 0, считывать не нужно.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   Во входных данных вводится последовательность целых чисел (каждое на новой строке), оканчивающаяся числом 0.
Число 0 в последовательность не входит.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Вывести длину последовательности.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1
7
9
0
5</pre>
     </td>
     <td>
      <pre>3</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
S = 0
a = 1
N = -1
while (a != 0):
	a = int(input())
	S = S + a
	N += 1
print(N)

# E
<html>
 <body>
  <p>
   На вход программе подается последовательность чисел, заканчивающихся нулем. Сам ноль не входит в последовательность. Найти среднее значение последовательности.
Для округления использовать функцию round(x, n). Где x - число, n - количество знаков после запятой.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   Последовательность чисел, заканчивающихся нулем. Одно число в строку.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Одно число — среднее значение. Округлить до двух цифр после запятой.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>4
8
5
0</pre>
     </td>
     <td>
      <pre>5.67</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
S = 0
a = 1
N = -1
while (a != 0):
	a = int(input())
	S = S + a
	N += 1
Av = float(S / N)
Avr = round(Av, 2)
print(Avr)

# F
<html>
 <body>
  <p>
   Дано натуральное число
   <em>
    N
   </em>
   . Выведите слово
   <strong>
    YES
   </strong>
   , если число
   <em>
    N
   </em>
   является точной степенью двойки, или слово
   <strong>
    NO
   </strong>
   в противном случае.
  </p>
  <p>
   <strong>
    ВАЖНО!
   </strong>
   В данной задаче необходимо использовать цикл. В этой задаче нельзя использовать функцию
   <strong>
    pow
   </strong>
   . Инструкция
   <strong>
    if
   </strong>
   должна находиться после цикла.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   На вход программе подается натуральное число
   <em>
    N
   </em>
   , не превышающее 10000.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Программа печатает
   <strong>
    YES
   </strong>
   если число является точной степенью двойки, иначе
   <strong>
    NO
   </strong>
   .
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>8</pre>
     </td>
     <td>
      <pre>YES</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>3</pre>
     </td>
     <td>
      <pre>NO</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
N = int(input())
A = 1
temp = 0
while (1+1==2):
	A = A * 2
	if A == N:
		temp = 1
		break
	if A >= 10000:
		break
if temp == 1:
	print('YES')
else:
	print('NO')

# G
<html>
 <body>
  <p>
   Дан список точек плоскости с целочисленными координатами.
  </p>
  <p>
   Необходимо определить номер координатной четверти K, в которой находится больше всего точек.
  </p>
  <p>
   Точки, хотя бы одна из координат которых равна нулю, считаются не принадлежащими ни одной четверти и не рассматриваются.
  </p>
  <p>
   Если одновременно в нескольких четвертях одинаковое и при этом максимальное количество точек, то вывести только первую по номеру.
  </p>
  <p>
   <em>
    Замечание:
   </em>
   в данной задаче можно обойтись без использования массива — использовать отдельные четыре счётчика.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   В первой строке вводится одно целое положительное число – количество точек N.
  </p>
  <p>
   Каждая из следующих N строк содержит координаты очередной точки – два целых числа (первое – координата x, второе – координата y).
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   В одной строке выводятся номер координатной четверти K, в которой находится больше всего точек и количество точек в ней.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>7
-3 4
1 2
1 1
0 4
-2 -3
-6 8
-12 1</pre>
     </td>
     <td>
      <pre>2 3</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>3
-5 -5
-5 -2
1 1</pre>
     </td>
     <td>
      <pre>3 2</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
N = int(input())
k1 = 0
k2 = 0
k3 = 0
k4 = 0
for i in range(N):
	x, y = input().split()
	x = int(x)
	y = int(y)
	if (x != 0) and (y != 0):
		if (x > 0) and (y > 0):
			k1 += 1
		if (x < 0) and (y > 0):
			k2 += 1
		if (x < 0) and (y < 0):
			k3 += 1
		if (x > 0) and (y < 0):
			k4 += 1
M = max(k1, k2, k3, k4)
if (k1 == M):
	print(1, k1)
if (k2 == M) and (k1 != M):
	print(2, k2)
if (k3 == M) and (k2 != M) and (k1 != M):
	print(3, k3)
if (k4 == M) and (k3 != M) and (k2 != M) and (k1 != M):
	print(4, k4)

# H
<html>
 <body>
  <p>
   Найти максимальное число в последовательности чисел, заканчивающейся нулем. Сам ноль не входит в последовательность.
Каждое из чисел не превосходит по модулю 10000. 
Обратите внимание, что числа могут быть отрицательными.
  </p>
  <p>
   NB! При решении этой задачи не требуется использовать массивы (списки)!
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   Последовательность целых чисел, заканчивающихся нулем. Одно число в строку.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Одно число — максимальное значение.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>4
8
5
0</pre>
     </td>
     <td>
      <pre>8</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
a = 1
N = -1
while (1+1==2):
	a = int(input())
	if a==0:
		break
	N += 1
	if (N==0):
		Max = a
	if a >= Max:
		Max = a
print(Max)

# I
<html>
 <body>
  <p>
   В некотором физическом эксперименте показания прибора снимались с частотой 5 измерений в секунду. Эксперимент проводился в течение довольно большого времени, и в результате накопилось очень много данных. Ученых, которые проводили данный эксперимент, очень интересует, какое максимальное значение измеряемой величины достигалось во время измерения. Но вот беда: на остановку установки также требуется секунда времени, и в течение этого времени с установки могут приходить совершенно любые значения величины. В связи с этим, показания последних 5 измерений учитывать при поиске максимального значения не следует.
  </p>
  <p>
   Вам необходимо написать программу, которая в данном потоке чисел заранее неизвестной длины находит максимальное значение, отбрасывая при этом последние 5 измерений.
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   На вход вашей программе передается последовательность натуральных чисел -- результаты измерений. Каждое новое число передается с новой строки. 
Гарантируется, что длина входной последовательности не меньше 6 и не превосходит 10
   <sup>
    6
   </sup>
   .
На конце последовательности передается число 0.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Программа должна вывести на экран одно число -- максимальное значение входной последовательности за исключением последних 5 элементов.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1
2
3
4
5
6
0</pre>
     </td>
     <td>
      <pre>1</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1
5
2
15
373
232
43
21
5433
5312
0</pre>
     </td>
     <td>
      <pre>373</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
a = 1
N = 1
a1 = 0
a2 = 0
a3 = 0
a4 = 0
a5 = 0
a6 = 0
Max = 0
while (a != 0):
	a6 = a5
	a5 = a4
	a4 = a3
	a3 = a2
	a2 = a1
	a1 = a
	a = int(input())
	if (N == 7):
		Max = a6
	if (N > 7):
		if (a6 > Max):
			Max = a6
	N += 1
print(Max)

# J
<html>
 <body>
  <h1>
   Сбой конвейера
  </h1>
  <p>
   На заводе по производству проигрывателей аудиокассет сборка готовой продукции производится на конвейере. На последнем этапе сборки на каждое изделие наносится уникальный идентификационный номер, равный порядковому номеру произведенного проигрывателя. При изготовлении очередной партии проигрывателей где-то в середине процесса произошел сбой, и одно из устройств не было помечено своим номером. После производства эта партия была упакована и отправлена на склад. При упаковке устройства перемешались. При разгрузке на складе было обнаружено, что на одно из устройств не нанесена маркировка. Помогите работникам склада определить номер этого устройства.
  </p>
  <p>
   Вам подается на вход последовательность идентификационных номеров, заканчивающаяся нулем. Необходимо определить номер устройства, на котором произошел сбой. Длина последовательности не меньше 2 и не превосходит 10
   <sup>
    5
   </sup>
  </p>
  <h3>
   Формат входных данных
  </h3>
  <p>
   Последовательность натуральных чисел, заканчивающася нулем.
  </p>
  <h3>
   Формат выходных данных
  </h3>
  <p>
   Одно число - номер устройства, на котором произошел сбой.
  </p>
  <h3>
   Примеры
  </h3>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>1
3
0</pre>
     </td>
     <td>
      <pre>2</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
  <table class="example">
   <thead>
    <tr>
     <td>
      Ввод
     </td>
     <td>
      Вывод
     </td>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <pre>4
2
1
7
5
6
0</pre>
     </td>
     <td>
      <pre>3</pre>
     </td>
    </tr>
   </tbody>
  </table>
  <br/>
 </body>
</html>

In [ ]:
N = 0
a = 1
S = 0
while (1+1==2):
    a = int(input())
    if a == 0:
        break
    if (N == 0):
        Max = a
        Min = a
    if a > Max:
    	Max = a
    if a < Min:
        Min = a
    S = S + a
    N += 1
Minx = Min - 1
Snat = (Max*(Max+1))/2 - (Minx*(Minx+1))/2
miss = int(Snat - S)
print(miss)